version: '2.2'
services:
  ros2:
    build: .
    #image:
    command: tail -f /dev/null
    privileged: true
    env_file:
      - ros.env
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
      - /dev:/dev
    environment:
        # - DISPLAY=host.docker.internal:0
      - DISPLAY=${IP}:0.0
       #networks:
        #- x11
    network_mode: host
    #restart: always

  ros2_novnc:  
    image: theasp/novnc:latest
    #restart: always
    env_file:
      - novnc.env
    ports:
      - "8080:8080"
    networks:
       x11:
          ipv4_address: ${IP}

networks:
    x11:
       enable_ipv6: false
       ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"
